### ISSUE TITLE
db hint

### ISSUE THREAD

**Issue by vitaly-t** [rob-ng/player-count#1]
https://github.com/rob-ng/player-count/blob/5e3db7a25bba918cfd4800cef0773c3f9487d845/models/utilities/populate/populate-all-games.js#L26

be careful with the console output, you will be spending at least 90% of time there, because the console is super slow, and you are trying to write into the console for every index.

And if you want really good performance there, you are better off concatenating inserts into batches of 1,000 - 10,000 records and execute each as a single multi-row insert.

Check out [Performance Boost](https://github.com/vitaly-t/pg-promise/wiki/Performance-Boost).

**Comment by rob-ng** [comment]
Hi Vitaly,

Thank you for bringing this up. I'd initially tried concatenating inserts but was getting syntax errors I wasn't able to source. I've since adopted your 'Inserts' function and reworked my code and performance has massively improved.
Also, thank you for your library - it's awesome.

Rob
